const MODO = Object.freeze({
  NORMAL: 1,
  CADASTRO: 2,
  LOGIN: 3,
  DETALHES: 4,
  EVENTO: 5,
  MINHA_CONTA: 6,
  ADMINISTRADOR: 7,
  FINALIZACAO: 8,
  MEUS_PEDIDOS: 9,
  CATEGORIAS_EVENTO: 10,
  DETALHE_PEDIDO: 11,
  MEUS_DADOS: 12,
  CADASTRO_EVENTOS: 13,
  ADMINISTRADORES: 14,
  COMPRADORES: 15,
  PRODUTORAS: 16,
  MEUS_INGRESSOS: 17,
  CONFERENCIA: 18,
  UTILIZACAO: 19,
  GERENCIA_EVENTOS: 20,
});

export default MODO;
